name: mynode
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  collection: ^1.15.0
  intl: ^0.17.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0
  get_it: ^7.2.0
  go_router: ^3.0.4
  flutter_colorpicker: ^1.0.3

  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0

  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  fast_i18n: ^5.11.0
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  build_runner: ^2.1.7
  mockito: ^5.1.0
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true